import { Show } from '@/types/Show'

export const showsMock: Show[] = [
  {
    id: 1,
    name: 'Breaking Bad',
    rating: { average: 9.5 },
    summary: '',
    network: null,
    type: '',
    language: 'English',
    status: '',
    updated: 0,
    averageRuntime: null,
    url: '',
    genres: ['Crime', 'Drama'],
    schedule: { time: '22:00', days: ['Monday', 'Tuesday'] },
    officialSite: 'https://www.officialsite.com',
    premiered: '2008-01-20',
    ended: '2013-09-29',
    image: { medium: 'image-url-medium', original: 'image-url-original' },
  },
  {
    id: 2,
    name: 'Stranger Things',
    rating: { average: 8.7 },
    summary: '',
    network: null,
    type: '',
    language: 'English',
    status: '',
    updated: 0,
    averageRuntime: null,
    url: '',
    genres: ['Crime', 'Drama'],
    schedule: { time: '22:00', days: ['Monday', 'Tuesday'] },
    officialSite: 'https://www.officialsite.com',
    premiered: '2008-01-20',
    ended: '2013-09-29',
    image: { medium: 'image-url-medium', original: 'image-url-original' },
  },
]
